# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - rules/cpu.rule
  - rules/memory.rule
  - rules/disk.rule
  - rules/instance.rule

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    target_groups:
      - targets: ['localhost:9090']

  - job_name: 'all_ec2_services'
    file_sd_configs:
      - names: ['/opt/prometheus/tgroups/*.json']
