# the global config
global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files:
  - rules/cpu.rule
  - rules/disk.rule
  - rules/instance.rule
  - rules/memory.rule

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ec2_services'
    ec2_sd_configs:
      - region: eu-west-1
        port: 6263
      - region: eu-west-1
        port: 6262
      - region: eu-west-1
        port: 2379
    relabel_configs:
      - source_labels: [__meta_ec2_tag_platform]
        regex: PLATFORM_TAG_REGEX
        target_label: platform
      - source_labels: [__meta_ec2_tag_environment]
        regex: ENVIRONMENT_TAG_REGEX
        target_label: environment
      - source_labels: [__meta_ec2_tag_platform]
        regex: PLATFORM_TAG_REGEX
        action: keep
        target_label: platform
      - source_labels: [__meta_ec2_tag_environment]
        regex: ENVIRONMENT_TAG_REGEX
        action: keep
      - source_labels: [__meta_ec2_availability_zone]
        target_label: az
