global:
smtp_smarthost: 'smtp.office365.com'
smtp_from: 'alertmanager@example.org'

route:
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: MSteamsEmail

receivers:
- name: 'MSteamsEmail'
  email_configs:
  - to: 'TEAMS_EMAIL'
  - from: 'sender@email.com'

- name: 'MSteamsWebhook'
  webhook_configs:
  - url: "TEAMS_WEB_HOOK"
