global:

# The directory from which notification templates are read.
templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: MSteamsEmail

receivers:
- name: 'MSteamsEmail'
  email_configs:
  - to: 'TEAMS_EMAIL'
    from: 'alertmanager@prometheus.efset.org'
    smarthost: smtp.gmail.com:587
    auth_username: 'EMAIL_ACCOUNT'
    auth_identity: 'EMAIL_ACCOUNT'
    auth_password: 'EMAIL_AUTH_TOKEN'

- name: 'MSteamsWebhook'
  webhook_configs:
  - url: "TEAMS_WEB_HOOK"
