global:
route:
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: Prometheus_Alertmanager
receivers:
  - name: Prometheus_Alertmanager
    webhook_configs:
      - url: "TEAMS_WEB_HOOK"
