global:
  smtp_smarthost: 'smtp.office365.com:587'
  smtp_from: 'alertmanager@example.org'

# The directory from which notification templates are read.
templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: MSteamsEmail

receivers:
- name: 'MSteamsEmail'
  email_configs:
  - to: 'TEAMS_EMAIL'

- name: 'MSteamsWebhook'
  webhook_configs:
  - url: "TEAMS_WEB_HOOK"
