# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    target_groups:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    target_groups:
      - targets: ['192.168.99.100:6262']

  - job_name: 'prom-node-exporter'
    target_groups:
      - targets: ['192.168.99.100:6263']
